package com.interviewprep.backend.service.impl;

import com.interviewprep.backend.dto.QuestionCreateDTO;
import com.interviewprep.backend.service.QuestionAiService;
import lombok.RequiredArgsConstructor;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;

@Service
@RequiredArgsConstructor
public class QuestionAiServiceImpl implements QuestionAiService {

    @Value("${app.openai.api-key}")
    private String apiKey;

    @Value("${app.openai.model}")
    private String model;

    @Override
    public List<QuestionCreateDTO> generateQuestionsForInterview(
            String category, String difficulty, Integer numberOfQuestions) {
        
        List<QuestionCreateDTO> questions = new ArrayList<>();
        
        String prompt = String.format(
            "Generate %d interview questions for category '%s' with difficulty level '%s'. " +
            "For each question, provide: title, description, hints, and expected answer. " +
            "Format as JSON array.",
            numberOfQuestions, category, difficulty
        );

        try {
            // Call OpenAI API
            String response = callOpenAiApi(prompt);
            questions = parseQuestionsFromResponse(response);
        } catch (Exception e) {
            throw new RuntimeException("Failed to generate questions using AI", e);
        }

        return questions;
    }

    @Override
    public String generateExpectedAnswer(String questionTitle, String category) {
        String prompt = String.format(
            "Provide a detailed answer for the interview question: '%s' in the '%s' category.",
            questionTitle, category
        );

        try {
            return callOpenAiApi(prompt);
        } catch (Exception e) {
            throw new RuntimeException("Failed to generate answer using AI", e);
        }
    }

    private String callOpenAiApi(String prompt) {
        // TODO: Implement actual OpenAI API call
        // For now, return mock response
        return "Mock AI response: " + prompt;
    }

    private List<QuestionCreateDTO> parseQuestionsFromResponse(String response) {
        List<QuestionCreateDTO> questions = new ArrayList<>();
        
        // TODO: Parse JSON response from OpenAI and convert to QuestionCreateDTO
        // This is a simplified version
        
        QuestionCreateDTO question = QuestionCreateDTO.builder()
                .title("Sample AI Generated Question")
                .description("This is a sample question generated by AI")
                .hints("Think about core concepts")
                .expectedAnswer("Detailed expected answer")
                .category("General")
                .difficulty("MEDIUM")
                .estimatedTimeMinutes(5)
                .build();
        
        questions.add(question);
        return questions;
    }
}
