# Development Profile
spring.datasource.url=jdbc:postgresql://localhost:5432/interview_prep_db
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.root=DEBUG
